apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-roll-dice
  labels:
    app: stats-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-deploy
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/app/main"
      labels:
        app: stats-deploy
    spec:
      containers:
        - name: stats
          image: docker.io/marcinziolkowski/go-auto-dice:3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  selector:
    app: stats-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-nodeport
spec:
  type: NodePort
  ports:
    - name: roll
      port: 8080
      targetPort: 80
      nodePort: 30001
  selector:
    app: stats-deploy
