version: "3.9"

networks:
  default:
    name: randomize-service
    driver: bridge

services:
  randomize-service:
    depends_on:
      - jaeger
    image: marcinziolkowski/http-randomizer:latest
    pid: "host"
    ports:
      - "8080:8080"
    volumes:
      - shared-data:/app
      - /proc:/host/proc
  go-auto:
    depends_on:
      - randomize-service
    image: marcinziolkowski/auto-go-instrumentation:0.2.1
    privileged: true
    pid: "host"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_GO_AUTO_TARGET_EXE=/app/main
      - OTEL_SERVICE_NAME=randomize-service
      - OTEL_PROPAGATORS=tracecontext,baggage
    volumes:
      - shared-data:/app
      - /proc:/host/proc

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped


volumes:
  shared-data: