apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: go-auto
  name: go-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go-auto
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/roll: "true"
        io.kompose.service: go-auto
    spec:
      containers:
        - env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: /app/main
            - name: OTEL_PROPAGATORS
              value: tracecontext,baggage
            - name: OTEL_SERVICE_NAME
              value: rolldice
          image: go-auto
          name: go-auto
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/proc
              name: go-auto-claim0
      restartPolicy: Always
      volumes:
        - name: go-auto-claim0
          persistentVolumeClaim:
            claimName: go-auto-claim0
