apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: rolldice
  name: rolldice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rolldice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/roll: "true"
        io.kompose.service: rolldice
    spec:
      containers:
        - image: rolldice
          name: rolldice
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /host/proc
              name: rolldice-claim0
      restartPolicy: Always
      volumes:
        - name: rolldice-claim0
          persistentVolumeClaim:
            claimName: rolldice-claim0
