apiVersion: v1
kind: Service
metadata:
name: sample-go-app-all-in-one
labels:
  component: go-sample-app
spec:
ports:
  - name: collector
    port: 14250
    protocol: TCP
    targetPort: 14250
selector:
  component: go-sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: sample-go-app-all-in-one
labels:
  component: go-sample-app
spec:
replicas: 1
selector:
  matchLabels:
    component: go-sample-app
template:
  metadata:
    annotations:
      instrumentation.opentelemetry.io/inject-go: "true"
      instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/app/main"
    labels:
      component: go-sample-app
  spec:
    containers:
      - image: marcinziolkowski/go-auto-dice
        name: go-app
        ports:
          # - containerPort: 16686
          # - containerPort: 14268
          - containerPort: 14250
